"""add tool call id

Revision ID: dfc8b8274754
Revises: d1a63b10840c
Create Date: 2026-08-14 22:51:30.841714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc8b8274754'
down_revision: Union[str, Sequence[str], None] = 'd1a63b10840c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_call_id')
    # ### end Alembic commands ###
