"""add google accounts

Revision ID: f69589b05bbe
Revises: e4c38578975c
Create Date: 2026-08-14 21:43:52.149770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69589b05bbe'
down_revision: Union[str, Sequence[str], None] = 'e4c38578975c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_user_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_accounts_google_user_id'), 'google_accounts', ['google_user_id'], unique=True)
    op.create_index(op.f('ix_google_accounts_user_id'), 'google_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_accounts_user_id'), table_name='google_accounts')
    op.drop_index(op.f('ix_google_accounts_google_user_id'), table_name='google_accounts')
    op.drop_table('google_accounts')
    # ### end Alembic commands ###
